### ISSUE TITLE
Character encoding not handled

### ISSUE THREAD

**Issue by daltones** [Gert-dev/php-integrator-linter#32]
Seems like the linter returns indexes based on bytes. When the file is UTF-8 encoded and has multibyte chars lint marks appear at wrong positions.

```php
<?php

// Some comment with two double-byte chars: ç ñ
function foo(BarClass $param) {
//             ^^^^^^^^ "BarClass was not found" with the lint mark two chars ahead
```

**Comment by Gert-dev** [comment]
You have in fact uncovered a larger issue in the base package: it turns out all the offsets returned by the parser back-end are byte offsets (and all calculations using it are assumed to be the same), whereas the offsets being passed in from and used by the CoffeeScript side are character offsets. By consequence, it is likely you will encounter other strange problems as well, because or minor differences in offsets.

I'll need to rewrite the back end to properly transition between the two types of offsets.

**Comment by daltones** [comment]
Thanks for the fast reply!

Understood. Probably you already realize that, but just complementing: I saw in the code that _parse errors_ are returned by backend already in `line:column` offsets, provided by an external PHP parser library. So in many more cases parse error marks will appear okay, just because of line splitting. But it still returns byte offsets and it can lead to wrong positions.

**Comment by Gert-dev** [comment]
This should be fixed with base 1.0.4, could you confirm?

**Comment by daltones** [comment]
Unfortunately it's not working correctly yet. I also tried to Force Index Project, but offsets are still wrong.

All php files of my project use UTF-8 encoding.
`php-integrator-base`: 1.0.4
`php-integrator-linter`: 1.0.0 (git b7d177c)
`atom`: 1.8.0

Btw, `php-integrator-linter` does not upgraded to 1.0.0 automatically (like all others `php-integrator-*`). I had to install from github repo.

**Comment by Gert-dev** [comment]
Oops, I forgot to publish a new patch release of this package to go with the adjustments from the base package. Could you give 1.0.1 a whirl?

**Comment by daltones** [comment]
Yeah! Now it works good! :smiley:

Again, thanks for these excellent packages! :)

**Comment by Gert-dev** [comment]
Great, thanks for taking the time to report issues!
